<?php
echo '<?xml version = "1.0" encoding= "UTF-8" ?>' ;
echo $this->doctype();
$this->layout()->nav = $this->action('render', 'menu', null, array('menu' => $this->mainMenuId));
$this->layout()->adminMenu = $this->action('render', 'menu', null, array('menu' => $this->adminMenuId));
$this->layout()->userForm = $this->action('index', 'user');
//$this->layout()->userForm = $this->action('register', 'register');
?>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php
			echo $this->headTitle();
			echo $this->headScript();
			// add a link to the site style sheet
			//$this->headLink()->appendStylesheet('/css/layout.css');
			$this->loadSkin($this->skin);
			echo $this->headLink();
			?>
	</head>
	<body>
		<div id= "pageWrapper">
			<div id="header">
				
			</div>
			<div id = "nav">
				<?php echo $this->layout()->nav;?>
			</div>
			<div id = "banner">
				
			</div>
			<div id= 'searchForm'>
					
					<?php
						$searchForm = new Application_Form_SearchForm();
						$searchForm->setAction('/search');
						echo $searchForm;
					?>
					
			</div>
			<div id = "sidebar">
				<div id = "subNav">
					<?php echo $this->layout()->subNav;?>&nbsp;
				</div>
				<div id = "adminMenu">
					<?php echo $this->layout()->adminMenu;?>&nbsp;
				</div>
				<div id= "userForm">
					<?php echo $this->layout()->userForm;?>&nbsp;
				</div>
				
                <div id= "feeds">
                	<h2>Feeds</h2>
                    <p><a href="/feed/rss">Click Here</a> to subscribe to our RSS feed. </p>
                </div>
			</div>
			<div id = "main">
				<?php echo $this->layout()->content;?>&nbsp;
			</div>
			<div id = "footer">
				<p><em>Powered by the Fexio ICT Center</em></p>
			</div>
		</div>
	</body>
</html>