<h2>Current Users</h2>
<?php
if ($this->users != null) {
?>

<table class = 'spreadsheet' cellpadding = '0' cellspacing = '0'>
	<tr>
		<th>Links</th>
		<th>Last Name</th>
		<th>First Name</th>
		<th>Username</th>
		<th>Role</th>
	</tr>
	<?php echo $this->partialLoop('partials/_user-row.phtml', $this->users);?>
</table>
<?php } else{
echo  'You do not have any users yet. '

?>
<?php } ?>

 
<p><a href = '/user/register'>Create a new user</a></p>